"""add verified boolean to user

Revision ID: 274d23844768
Revises: 6d0f5f68ae9d
Create Date: 2024-12-12 08:15:52.011888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '274d23844768'
down_revision: Union[str, None] = '6d0f5f68ae9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified_email', sa.Boolean(), nullable=True))
    op.execute('UPDATE users SET verified_email=false')
    op.alter_column('users', sa.Column('verified_email', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified_email')
    # ### end Alembic commands ###
